-keep class com.foxpoint.chattery.GameUtils, com.foxpoint.chattery.LoginUtils, com.foxpoint.chattery.ServerUtils, !com.foxpoint.**, ** { *; }
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable